# Generated by Django 5.x — ВКР-029
# Начальная схема БД: 14 таблиц, 21 индекс

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [

        # ─── Справочники ──────────────────────────────────────────────────────

        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Роль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
            },
        ),

        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('level', models.IntegerField(verbose_name='Уровень приоритета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
                'db_table': 'priority',
                'ordering': ['level'],
            },
        ),

        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),

        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
            },
        ),

        # ─── Пользователи ─────────────────────────────────────────────────────

        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('role', models.ForeignKey(
                    default=3,
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='core.role',
                    verbose_name='Роль',
                )),
                ('groups', models.ManyToManyField(
                    blank=True,
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.group',
                    verbose_name='groups',
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.permission',
                    verbose_name='user permissions',
                )),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),

        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),

        # ─── Услуги ───────────────────────────────────────────────────────────

        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='core.category',
                    verbose_name='Категория',
                )),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'service',
            },
        ),

        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='service_category_idx'),
        ),

        # ─── Заявки ───────────────────────────────────────────────────────────

        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(
                    choices=[
                        ('new', 'Новая'),
                        ('in_progress', 'В работе'),
                        ('resolved', 'Решена'),
                        ('closed', 'Закрыта'),
                        ('cancelled', 'Отменена'),
                    ],
                    default='new',
                    max_length=50,
                    verbose_name='Статус',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='tickets',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Клиент',
                )),
                ('service', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='core.service',
                    verbose_name='Услуга',
                )),
                ('manager', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='managed_tickets',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Менеджер',
                )),
                ('priority', models.ForeignKey(
                    default=2,
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='core.priority',
                    verbose_name='Приоритет',
                )),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),

        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='project_user_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='project_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='project_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='project_created_idx'),
        ),

        # ─── Контент ──────────────────────────────────────────────────────────

        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),

        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author'], name='news_author_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='news_published_idx'),
        ),

        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='core.category',
                    verbose_name='Категория',
                )),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),

        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='article_category_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='article_author_idx'),
        ),

        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.article',
                )),
                ('tag', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.tag',
                )),
            ],
            options={
                'db_table': 'article_tag',
            },
        ),

        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                through='core.ArticleTag',
                to='core.tag',
                verbose_name='Теги',
            ),
        ),

        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),

        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['article'], name='articletag_article_idx'),
        ),
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['tag'], name='articletag_tag_idx'),
        ),

        # ─── Коммуникация ─────────────────────────────────────────────────────

        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь',
                )),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
            },
        ),

        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['user'], name='contact_user_idx'),
        ),

        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='core.project',
                    verbose_name='Заявка',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),

        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['project'], name='comment_project_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comment_user_idx'),
        ),

        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(verbose_name='Размер (байт)')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attachments',
                    to='core.project',
                    verbose_name='Заявка',
                )),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'attachment',
            },
        ),

        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['project'], name='attachment_project_idx'),
        ),

        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notifications',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь',
                )),
                ('project', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.project',
                    verbose_name='Заявка',
                )),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),

        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notification_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['project'], name='notification_project_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notification_is_read_idx'),
        ),

        # ─── Начальные данные ─────────────────────────────────────────────────
        # Создаём базовые роли до того, как будет создан первый пользователь.
        # id=1 admin, id=2 manager, id=3 client — соответствует default=3 в User.role
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'Role').objects.bulk_create([
                apps.get_model('core', 'Role')(id=1, name='admin',   description='Администратор системы'),
                apps.get_model('core', 'Role')(id=2, name='manager', description='Менеджер (сотрудник)'),
                apps.get_model('core', 'Role')(id=3, name='client',  description='Клиент (пользователь)'),
            ]),
            reverse_code=lambda apps, schema_editor: apps.get_model('core', 'Role').objects.filter(
                name__in=['admin', 'manager', 'client']
            ).delete(),
        ),
    ]
