# Generated by Django 5.2.1 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='article_categor_d02163_idx',
            old_name='article_category_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='article_author__cafbdc_idx',
            old_name='article_author_idx',
        ),
        migrations.RenameIndex(
            model_name='articletag',
            new_name='article_tag_article_c8a6cb_idx',
            old_name='articletag_article_idx',
        ),
        migrations.RenameIndex(
            model_name='articletag',
            new_name='article_tag_tag_id_4f1592_idx',
            old_name='articletag_tag_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachment_project_422f5b_idx',
            old_name='attachment_project_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_project_c89ac9_idx',
            old_name='comment_project_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_user_id_bdf487_idx',
            old_name='comment_user_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_mes_user_id_98801f_idx',
            old_name='contact_user_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_author__0a3ad8_idx',
            old_name='news_author_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_publish_efe204_idx',
            old_name='news_published_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_3cbd6f_idx',
            old_name='notification_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_project_b7cac0_idx',
            old_name='notification_project_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_8a483f_idx',
            old_name='notification_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_user_id_a20c46_idx',
            old_name='project_user_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_manager_2eed63_idx',
            old_name='project_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_priorit_08d6b1_idx',
            old_name='project_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_status_37437c_idx',
            old_name='project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_created_c5c827_idx',
            old_name='project_created_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_categor_7052e1_idx',
            old_name='service_category_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_role_id_9c10d6_idx',
            old_name='user_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_email_7bbb4c_idx',
            old_name='user_email_idx',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='Размер (байт)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
